{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: failing for demo purposes\nassert 0", "trace": "def test_2():\n        print ('in test_2')\n        time.sleep(1)\n        print ('after 1 sec')\n        time.sleep(1)\n        print ('after 2 sec')\n        time.sleep(1)\n        print ('after 3 sec')\n>       assert 0, 'failing for demo purposes'\nE       AssertionError: failing for demo purposes\nE       assert 0\n\ntest_demo.py:22: AssertionError"}, "start": 1663575943000, "stop": 1663575946027, "uuid": "0ec02492-518e-4360-9740-7374d3b24542", "historyId": "c0c0a28707fc9d4d177aa067505be564", "testCaseId": "ec16501b15041eec49611641414c42ee", "fullName": "test_case.demo_case.stu_demo.test_demo#test_2", "labels": [{"name": "parentSuite", "value": "test_case.demo_case.stu_demo"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "我不帅"}, {"name": "thread", "value": "9948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.demo_case.stu_demo.test_demo"}]}