{"name": "test_cart[login_r2]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因，密码为空\nassert False", "trace": "login_r = False\n\n    @pytest.mark.parametrize('login_r',test_user_data,indirect=True)\n    def test_cart(login_r):\n        #登陆用例\n        a=login_r\n        print('测试用例中login_r的返回值%s'%a)\n>       assert a,'失败原因，密码为空'\nE       AssertionError: 失败原因，密码为空\nE       assert False\n\ntest_demo.py:25: AssertionError"}, "parameters": [{"name": "login_r", "value": "{'user': 'test01', 'password': ''}"}], "start": 1663565903410, "stop": 1663565903410, "uuid": "0c678bf3-26a5-43a1-a5cf-7001c74036df", "historyId": "81669221095529d610954080de51feb3", "testCaseId": "124c944f2deeaa7cf60b7014dcf5722a", "fullName": "test_case.demo_case.stu_demo.test_demo#test_cart", "labels": [{"name": "parentSuite", "value": "test_case.demo_case.stu_demo"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "我不帅"}, {"name": "thread", "value": "1356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.demo_case.stu_demo.test_demo"}]}